spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/crm_system
    driver-class-name: org.postgresql.Driver
    username: crm_user
    password: crm_password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    com.crm: DEBUG
    org.hibernate.SQL: DEBUG